FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libcairo2 \
    libcairo2-dev \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    libgobject-2.0-0 \
    libglib2.0-0 \
    libxml2 \
    libxslt1.1 \
    libharfbuzz0b \
    libfreetype6 \
    libfontconfig1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml .

RUN uv venv /opt/voucher-venv && \
    uv sync --python=/opt/voucher-venv/bin/python

ENV VIRTUAL_ENV=/opt/voucher-venv
ENV PATH="/opt/voucher-venv/bin:$PATH"

